version: '2'

services:
  postgres:
    image: postgres:9.6
    volumes: 
        # Create Test database on Postgresql
        - ./docker-airflow/pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
        - POSTGRES_USER=airflow
        - POSTGRES_PASSWORD=airflow
        - POSTGRES_DB=airflow
    ports:
        - "5432:5432"
  airflow-webserver:
    image: airflow-spark-container:latest
    restart: always
    depends_on:
        - postgres
    environment:
        - LOAD_EX=y
        - EXECUTOR=Local
    volumes:
        - ../Airflow_dags/dags:/usr/local/airflow/dags #DAG folder
        - ../Airflow_dags/spark/app:/usr/local/spark/app
        - ../Airflow_dags/spark/resources:/usr/local/spark/resources #Spark Scripts (Must be the same path in airflow and Spark Cluster)
    ports:
        - "8282:8282"
    command: webserver
    healthcheck:
        test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
        interval: 30s
        timeout: 30s
        retries: 3
  hdfs:
    image: hdfs-namenode:latest
    container_name: hdfs
    volumes:
      - ./HDFS/data:/hadoop/data
    environment:
      - CLUSTER_NAME=test
      - "HADOOP_CONF_DIR=/etc/hadoop"
      - "USER=root"
    ports:
      - "9000:9000"
      - "9870:9870"
      - "2222:22"
      
  spark:
    image: spark-custom:latest
    container_name: spark
    depends_on:
      - hdfs
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - CORE_CONF_fs_defaultFS=hdfs://hdfs:9000

    volumes:
      - ../Airflow_dags/spark/app:/usr/local/spark/app # Spark scripts folder (Must be the same path in airflow and Spark Cluster)
      - ../Airflow_dags/spark/resources:/usr/local/spark/resources #Resources folder (Must be the same path in airflow and Spark Cluster)
    ports:
      - '8080:8080'
      - "7077:7077"
  spark-worker-1:
    image: spark-custom:latest
    container_name: spark-worker1
    depends_on:
      - spark
    ports:
      - "8081:8081"
    environment:
      - SPARK_MASTER=spark://spark:7077
      - CORE_CONF_fs_defaultFS=hdfs://hdfs:9000
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=3G
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ../Airflow_dags/spark/app:/usr/local/spark/app # Spark scripts folder (Must be the same path in airflow and Spark Cluster)
      - ../Airflow_dags/spark/resources:/usr/local/spark/resources
  spark-worker-2:
    image: spark-custom:latest
    container_name: spark-worker2
    depends_on:
      - spark
    ports:
      - "8082:8081"
    environment:
      - SPARK_MASTER=spark://spark:7077
      - CORE_CONF_fs_defaultFS=hdfs://hdfs:9000
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=3G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ../Airflow_dags/spark/app:/usr/local/spark/app # Spark scripts folder (Must be the same path in airflow and Spark Cluster)
      - ../Airflow_dags/spark/resources:/usr/local/spark/resources
