FROM apache/airflow:latest
###############################
## Begin JAVA installation
###############################
# Java is required in order to spark-submit work
# Install OpenJDK-8
#USER root
#RUN sudo apt-get update && \
#    apt-get install -y software-properties-common && \
#    apt-get install -y gnupg2 && \
#    add-apt-repository "deb http://security.debian.org/debian-security stretch/updates main" && \ 
#    apt-get update && \
#    apt-get install -y openjdk-8-jdk
